name: Node.js Package

on:
  push:
    tags:
      - "v*" # for bumpp

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # env
      - name: Setup git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      # build
      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
      # publish
      - name: Publish Beta
        if: contains(github.event.release.name, 'beta') == true
        run: pnpm publish -r --access public --no-git-checks --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        if: contains(github.event.release.name, 'beta') == false
        run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
